apiVersion: v2
appVersion: 9.5.9096
description: A Helm chart for Kubernetes
name: webcerberus
version: 9.5.9096


dependencies:
  - name: solr
    version: 6.3.x
    repository: https://charts.bitnami.com/bitnami